name: Compile and test the app

on:
  workflow_call:

defaults:
  run:
    shell: "bash"

jobs:
  compile-and-test:
    permissions:
      contents: write
      id-token: write
      attestations: write
    
    env:
      NODE_NO_WARNINGS: 1
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      npm_config_audit: false
      npm_config_fund: false
      USE_HARD_LINKS: false

    runs-on: macos-15-intel

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=23.0.0"

      - run: npm install
      - run: npm run compile -- -p never
      - run: ls -lR dist/mac/denokv-gui-client.app/Contents/Resources/app.asar.unpacked/node_modules/@deno/kv-*
      - run: ls dist

      - name: Mount DMG
        run: |
          MOUNT_POINT=$(hdiutil attach ./dist/denokv-gui-client-1.10.0-mac-x64.dmg | grep Volumes | awk '{print $3}')
          echo "MOUNT_POINT=$MOUNT_POINT" >> $GITHUB_ENV

      - name: Where is the App
        run: echo "$MOUNT_POINT"

      - name: Where is the App
        run: ls "$MOUNT_POINT"

      - name: Install App
        run: cp -R "$MOUNT_POINT"/denokv-gui-client-1.10.0-mac-x64.app /Applications/

      # - name: Install App
      #   run: cp -R "$MOUNT_POINT"/denokv-gui-client.app /Applications/

      - name: Unmount DMG
        run: hdiutil detach "$MOUNT_POINT"

      - name: Remove Quarantine
        run: xattr -dr com.apple.quarantine /Applications/denokv-gui-client-1.10.0-mac-x64

      - name: Run App
        run: open /Applications/denokv-gui-client-1.10.0-mac-x64

      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: "dist/denokv-gui-client*, dist/latest*.yml"

      - name: Upload compiled app
        uses: actions/upload-artifact@v4
        with:
          name: macos-15-intel
          path: dist
