name: Build and release mac-x64 version

on:
  workflow_call:

defaults:
  run:
    shell: "bash"

jobs:
  compile-and-test:
    permissions:
      contents: write
      id-token: write
      attestations: write
    
    env:
      NODE_NO_WARNINGS: 1
      npm_config_audit: false
      npm_config_fund: false
      USE_HARD_LINKS: false

    runs-on: macos-15-intel

    steps:
      - name: 
        uses: actions/checkout@v4
        with:
          repository: AbdulrhmanGoni/denokv-gui-client
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: ">=23.0.0"

      - name: Install dependencies
        run: npm install

      - name: Install the "x86_64-apple-darwin" binary for "@deno/kv"
        run: |
          releaseUrl=https://api.github.com/repos/dhmeBrnawe/denokv-x64-mac-build/releases/latest
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -sSL --retry 3 --retry-delay 3 $releaseUrl -o release.json

          # Check release.json exists and is not empty
          if [ ! -s release.json ]; then
            echo "Failed to download release.json"
            exit 1
          fi

          # Extract the download URL of the first asset
          download_url=$(jq -r '.assets[0].browser_download_url' release.json)
          if [[ -z "$download_url" ]]; then
            echo "Failed to parse download_url from release.json"
            cat release.json
            exit 1
          fi

          # Download "deno-kv-napi.darwin-x64.node" binary
          binaryDist=./node_modules/@deno/kv-darwin-x64/deno-kv-napi.darwin-x64.node
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -L --retry 3 --retry-delay 3 -o $binaryDist $download_url

      - name: Build the app
        run: npm run compile -- -p never

      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: "dist/denokv-gui-client*, dist/latest*.yml"

      - name: Release the build
        run: gh release new test-mac-x64-build --repo $GITHUB_REPOSITORY dist/denokv-gui-client* dist/latest*.yml
        env:
          GH_TOKEN: ${{ github.token }}