name: Compile and test the app

on:
  workflow_call:

defaults:
  run:
    shell: "bash"

jobs:
  compile-and-test:
    permissions:
      contents: write
      id-token: write
      attestations: write
    
    env:
      NODE_NO_WARNINGS: 1
      npm_config_audit: false
      npm_config_fund: false
      USE_HARD_LINKS: false
      GH_TOKEN: ${{ github.token }}

    runs-on: macos-15-intel

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=23.0.0"

      - name: Install dependencies
        run: npm install

      - name: Install the "x86_64-apple-darwin" binary for "@deno/kv"
        run: |
          curl -sSL https://api.github.com/repos/dhmeBrnawe/denokv-x64-mac-build/releases/latest -o release.json
  
          # Check release.json exists and is not empty
          if [ ! -s release.json ]; then
            echo "Failed to download release.json"
            exit 1
          fi

          # Extract the download URL of the first asset
          download_url=$(jq -r '.assets[0].browser_download_url' release.json)
          if [[ -z "$download_url" ]]; then
            echo "Failed to parse download_url from release.json"
            cat release.json
            exit 1
          fi

          # Download "deno-kv-napi.darwin-x64.node" binary
          curl -L "$download_url" -o ./node_modules/@deno/kv-darwin-x64/deno-kv-napi.darwin-x64.node

      - name: Build the app
        run: npm run compile

      - run: ls -lR dist/mac/denokv-gui-client.app/Contents/Resources/app.asar.unpacked/node_modules/@deno/kv-*
      - run: ls dist

      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: "dist/denokv-gui-client*, dist/latest*.yml"

      - name: Release the build
        run: gh release new test-mac-x64-build --repo $GITHUB_REPOSITORY dist/denokv-gui-client* dist/latest*.yml
